<?php
/**
 * Created by PhpStorm.
 * User: Martin
 * Date: 14-5-22
 * Time: 下午3:03
 */
define('ERROR_CODE_OK', 200);
define('ERROR_CODE_FAIL', 201);
define('ERROR_CODE_PARAM_INVALID', 203);
define('ERROR_CODE_CONFIG_NOT_FOUND', 204);
define('ERROR_CODE_DATA_INVALID_CARD', 1408);
define('ERROR_CODE_DATA_INVALID_EQUIP', 1402);
define('ERROR_CODE_DATA_INVALID_DBALL', 1403);
define('ERROR_CODE_DATA_INVALID_ITEM', 1404);
define('ERROR_CODE_DATA_INVALID_KARIN', 1405);
define('ERROR_CODE_DATA_INVALID_DECK', 1406);
define('ERROR_CODE_DATA_INVALID_QUEST', 1407);
define('ERROR_CODE_DATA_INVALID_GUILD', 1408);
define('ERROR_CODE_DB_ERROR_MYSQL', 1501);
define('ERROR_CODE_DB_ERROR_REDIS', 1502);